### PR TITLE
_worker_ needs custom github access

### PR DESCRIPTION
**Pull request by davidszotten**

### CODE REVIEW

**Comment by junkafarian** [comment]
I'm getting major déjà vu here. Have we fixed this in another branch?

**Comment by junkafarian** [comment]
definitely looks like the right change though :shipit:

**Comment by davidszotten** [comment]
you referring to https://github.com/onefinestay/cinch/pull/34/files ? which "fixed" it in the wrong place. this is fixing that fix (hence "_worker_ needs")

**Comment by junkafarian** [comment]
how meta

**Pull request merged**
